--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2
projects:
  MagicWE2:
    path: ""
    libs:
      - src: BlockHorizons/libschematic/libschematic
        version: ^0.0.6
...
